import { CountryData } from "./country-model";

export const countryData: CountryData[] = [
    { "code": "+93", "short_code": "AF", "name": "Afghanistan", "min_length": 8, "max_length": 9 },
    { "code": "+355", "short_code": "AL", "name": "Albania", "min_length": 8, "max_length": 9 },
    { "code": "+213", "short_code": "DZ", "name": "Algeria", "min_length": 8, "max_length": 9 },
    { "code": "+1-684", "short_code": "AS", "name": "American Samoa", "min_length": 9, "max_length": 10 },
    { "code": "+376", "short_code": "AD", "name": "Andorra", "min_length": 8, "max_length": 9 },
    { "code": "+244", "short_code": "AO", "name": "Angola", "min_length": 8, "max_length": 9 },
    { "code": "+1-264", "short_code": "AI", "name": "Anguilla", "min_length": 9, "max_length": 10 },
    { "code": "+672", "short_code": "AQ", "name": "Antarctica", "min_length": 5, "max_length": 6 },
    { "code": "+1-268", "short_code": "AG", "name": "Antigua and Barbuda", "min_length": 9, "max_length": 10 },
    { "code": "+54", "short_code": "AR", "name": "Argentina", "min_length": 11, "max_length": 13 },
    { "code": "+374", "short_code": "AM", "name": "Armenia", "min_length": 7, "max_length": 8 },
    { "code": "+297", "short_code": "AW", "name": "Aruba", "min_length": 9, "max_length": 10 },
    { "code": "+61", "short_code": "AU", "name": "Australia", "min_length": 13, "max_length": 15 },
    { "code": "+43", "short_code": "AT", "name": "Austria", "min_length": 11, "max_length": 13 },
    { "code": "+994", "short_code": "AZ", "name": "Azerbaijan", "min_length": 8, "max_length": 9 },
    { "code": "+1-242", "short_code": "BS", "name": "Bahamas", "min_length": 9, "max_length": 10 },
    { "code": "+973", "short_code": "BH", "name": "Bahrain", "min_length": 7, "max_length": 8 },
    { "code": "+880", "short_code": "BD", "name": "Bangladesh", "min_length": 9, "max_length": 10 },
    { "code": "+1-246", "short_code": "BB", "name": "Barbados", "min_length": 9, "max_length": 10 },
    { "code": "+375", "short_code": "BY", "name": "Belarus", "min_length": 11, "max_length": 12 },
    { "code": "+32", "short_code": "BE", "name": "Belgium", "min_length": 8, "max_length": 9 },
    { "code": "+501", "short_code": "BZ", "name": "Belize", "min_length": 6, "max_length": 7 },
    { "code": "+229", "short_code": "BJ", "name": "Benin", "min_length": 7, "max_length": 8 },
    { "code": "+1-441", "short_code": "BM", "name": "Bermuda", "min_length": 9, "max_length": 10 },
    { "code": "+975", "short_code": "BT", "name": "Bhutan", "min_length": 7, "max_length": 8 },
    { "code": "+591", "short_code": "BO", "name": "Bolivia", "min_length": 7, "max_length": 8 },
    { "code": "+387", "short_code": "BA", "name": "Bosnia and Herzegovina", "min_length": 11, "max_length": 12 },
    { "code": "+267", "short_code": "BW", "name": "Botswana", "min_length": 8, "max_length": 9 },
    { "code": "+55", "short_code": "BR", "name": "Brazil", "min_length": 12, "max_length": 13 },
    { "code": "+246", "short_code": "IO", "name": "British Indian Ocean Territory", "min_length": 14, "max_length": 15 },
    { "code": "+1-284", "short_code": "VG", "name": "British Virgin Islands", "min_length": 9, "max_length": 10 },
    { "code": "+673", "short_code": "BN", "name": "Brunei", "min_length": 7, "max_length": 8 },
    { "code": "+359", "short_code": "BG", "name": "Bulgaria", "min_length": 9, "max_length": 10 },
    { "code": "+226", "short_code": "BF", "name": "Burkina Faso", "min_length": 7, "max_length": 8 },
    { "code": "+257", "short_code": "BI", "name": "Burundi", "min_length": 7, "max_length": 8 },
    { "code": "+855", "short_code": "KH", "name": "Cambodia", "min_length": 8, "max_length": 9 },
    { "code": "+237", "short_code": "CM", "name": "Cameroon", "min_length": 8, "max_length": 9 },
    { "code": "+1", "short_code": "CA", "name": "Canada", "min_length": 10, "max_length": 11 },
    { "code": "+238", "short_code": "CV", "name": "Cape Verde", "min_length": 7, "max_length": 8 },
    { "code": "+1-345", "short_code": "KY", "name": "Cayman Islands", "min_length": 9, "max_length": 10 },
    { "code": "+236", "short_code": "CF", "name": "Central African Republic", "min_length": 7, "max_length": 8 },
    { "code": "+235", "short_code": "TD", "name": "Chad", "min_length": 7, "max_length": 8 },
    { "code": "+56", "short_code": "CL", "name": "Chile", "min_length": 10, "max_length": 11 },
    { "code": "+86", "short_code": "CN", "name": "China", "min_length": 11, "max_length": 12 },
    { "code": "+61", "short_code": "CX", "name": "Christmas Island", "min_length": 13, "max_length": 14 },
    { "code": "+61", "short_code": "CC", "name": "Cocos Islands", "min_length": 13, "max_length": 14 },
    { "code": "+57", "short_code": "CO", "name": "Colombia", "min_length": 10, "max_length": 11 },
    { "code": "+269", "short_code": "KM", "name": "Comoros", "min_length": 7, "max_length": 8 },
    { "code": "+682", "short_code": "CK", "name": "Cook Islands", "min_length": 6, "max_length": 7 },
    { "code": "+506", "short_code": "CR", "name": "Costa Rica", "min_length": 8, "max_length": 9 },
    { "code": "+385", "short_code": "HR", "name": "Croatia", "min_length": 10, "max_length": 11 },
    { "code": "+53", "short_code": "CU", "name": "Cuba", "min_length": 9, "max_length": 10 },
    { "code": "+599", "short_code": "CW", "name": "Curacao", "min_length": 8, "max_length": 9 },
    { "code": "+357", "short_code": "CY", "name": "Cyprus", "min_length": 9, "max_length": 10 },
    { "code": "+420", "short_code": "CZ", "name": "Czech Republic", "min_length": 9, "max_length": 10 },
    { "code": "+243", "short_code": "CD", "name": "Democratic Republic of the Congo", "min_length": 8, "max_length": 9 },
    { "code": "+45", "short_code": "DK", "name": "Denmark", "min_length": 8, "max_length": 9 },
    { "code": "+253", "short_code": "DJ", "name": "Djibouti", "min_length": 7, "max_length": 8 },
    { "code": "+1-767", "short_code": "DM", "name": "Dominica", "min_length": 9, "max_length": 10 },
    { "code": "+1-809", "short_code": "DO", "name": "Dominican Republic", "min_length": 9, "max_length": 10 },
    { "code": "+670", "short_code": "TL", "name": "East Timor", "min_length": 8, "max_length": 9 },
    { "code": "+593", "short_code": "EC", "name": "Ecuador", "min_length": 9, "max_length": 10 },
    { "code": "+20", "short_code": "EG", "name": "Egypt", "min_length": 9, "max_length": 10 },
    { "code": "+503", "short_code": "SV", "name": "El Salvador", "min_length": 8, "max_length": 9 },
    { "code": "+240", "short_code": "GQ", "name": "Equatorial Guinea", "min_length": 7, "max_length": 8 },
    { "code": "+291", "short_code": "ER", "name": "Eritrea", "min_length": 7, "max_length": 8 },
    { "code": "+372", "short_code": "EE", "name": "Estonia", "min_length": 8, "max_length": 9 },
    { "code": "+251", "short_code": "ET", "name": "Ethiopia", "min_length": 9, "max_length": 10 },
    { "code": "+500", "short_code": "FK", "name": "Falkland Islands", "min_length": 8, "max_length": 9 },
    { "code": "+298", "short_code": "FO", "name": "Faroe Islands", "min_length": 6, "max_length": 7 },
    { "code": "+679", "short_code": "FJ", "name": "Fiji", "min_length": 7, "max_length": 8 },
    { "code": "+358", "short_code": "FI", "name": "Finland", "min_length": 10, "max_length": 11 },
    { "code": "+33", "short_code": "FR", "name": "France", "min_length": 11, "max_length": 12 },
    { "code": "+689", "short_code": "PF", "name": "French Polynesia", "min_length": 8, "max_length": 9 },
    { "code": "+241", "short_code": "GA", "name": "Gabon", "min_length": 8, "max_length": 9 },
    { "code": "+220", "short_code": "GM", "name": "Gambia", "min_length": 7, "max_length": 8 },
    { "code": "+995", "short_code": "GE", "name": "Georgia", "min_length": 8, "max_length": 9 },
    { "code": "+49", "short_code": "DE", "name": "Germany", "min_length": 11, "max_length": 12 },
    { "code": "+233", "short_code": "GH", "name": "Ghana", "min_length": 10, "max_length": 11 },
    { "code": "+350", "short_code": "GI", "name": "Gibraltar", "min_length": 8, "max_length": 9 },
    { "code": "+30", "short_code": "GR", "name": "Greece", "min_length": 10, "max_length": 11 },
    { "code": "+299", "short_code": "GL", "name": "Greenland", "min_length": 8, "max_length": 9 },
    { "code": "+1-473", "short_code": "GD", "name": "Grenada", "min_length": 9, "max_length": 10 },
    { "code": "+1-671", "short_code": "GU", "name": "Guam", "min_length": 9, "max_length": 10 },
    { "code": "+502", "short_code": "GT", "name": "Guatemala", "min_length": 8, "max_length": 9 },
    { "code": "+44", "short_code": "GG", "name": "Guernsey", "min_length": 10, "max_length": 11 },
    { "code": "+224", "short_code": "GN", "name": "Guinea", "min_length": 7, "max_length": 8 },
    { "code": "+245", "short_code": "GW", "name": "Guinea-Bissau", "min_length": 7, "max_length": 8 },
    { "code": "+592", "short_code": "GY", "name": "Guyana", "min_length": 7, "max_length": 8 },
    { "code": "+509", "short_code": "HT", "name": "Haiti", "min_length": 8, "max_length": 9 },
    { "code": "+504", "short_code": "HN", "name": "Honduras", "min_length": 8, "max_length": 9 },
    { "code": "+852", "short_code": "HK", "name": "Hong Kong", "min_length": 8, "max_length": 9 },
    { "code": "+36", "short_code": "HU", "name": "Hungary", "min_length": 9, "max_length": 10 },
    { "code": "+354", "short_code": "IS", "name": "Iceland", "min_length": 8, "max_length": 9 },
    { "code": "+91", "short_code": "IN", "name": "India", "min_length": 11, "max_length": 12 },
    { "code": "+62", "short_code": "ID", "name": "Indonesia", "min_length": 9, "max_length": 10 },
    { "code": "+98", "short_code": "IR", "name": "Iran", "min_length": 10, "max_length": 11 },
    { "code": "+964", "short_code": "IQ", "name": "Iraq", "min_length": 10, "max_length": 11 },
    { "code": "+353", "short_code": "IE", "name": "Ireland", "min_length": 9, "max_length": 10 },
    { "code": "+44", "short_code": "IM", "name": "Isle of Man", "min_length": 10, "max_length": 11 },
    { "code": "+972", "short_code": "IL", "name": "Israel", "min_length": 10, "max_length": 11 },
    { "code": "+39", "short_code": "IT", "name": "Italy", "min_length": 11, "max_length": 12 },
    { "code": "+225", "short_code": "CI", "name": "Ivory Coast", "min_length": 9, "max_length": 10 },
    { "code": "+1-876", "short_code": "JM", "name": "Jamaica", "min_length": 9, "max_length": 10 },
    { "code": "+81", "short_code": "JP", "name": "Japan", "min_length": 11, "max_length": 12 },
    { "code": "+44", "short_code": "JE", "name": "Jersey", "min_length": 10, "max_length": 11 },
    { "code": "+962", "short_code": "JO", "name": "Jordan", "min_length": 10, "max_length": 11 },
    { "code": "+7", "short_code": "KZ", "name": "Kazakhstan", "min_length": 11, "max_length": 12 },
    { "code": "+254", "short_code": "KE", "name": "Kenya", "min_length": 10, "max_length": 11 },
    { "code": "+686", "short_code": "KI", "name": "Kiribati", "min_length": 6, "max_length": 7 },
    { "code": "+383", "short_code": "XK", "name": "Kosovo", "min_length": 9, "max_length": 10 },
    { "code": "+965", "short_code": "KW", "name": "Kuwait", "min_length": 8, "max_length": 9 },
    { "code": "+996", "short_code": "KG", "name": "Kyrgyzstan", "min_length": 9, "max_length": 10 },
    { "code": "+856", "short_code": "LA", "name": "Laos", "min_length": 8, "max_length": 9 },
    { "code": "+371", "short_code": "LV", "name": "Latvia", "min_length": 8, "max_length": 9 },
    { "code": "+961", "short_code": "LB", "name": "Lebanon", "min_length": 8, "max_length": 9 },
    { "code": "+266", "short_code": "LS", "name": "Lesotho", "min_length": 8, "max_length": 9 },
    { "code": "+231", "short_code": "LR", "name": "Liberia", "min_length": 7, "max_length": 8 },
    { "code": "+218", "short_code": "LY", "name": "Libya", "min_length": 8, "max_length": 9 },
    { "code": "+423", "short_code": "LI", "name": "Liechtenstein", "min_length": 8, "max_length": 9 },
    { "code": "+370", "short_code": "LT", "name": "Lithuania", "min_length": 8, "max_length": 9 },
    { "code": "+352", "short_code": "LU", "name": "Luxembourg", "min_length": 10, "max_length": 11 },
    { "code": "+853", "short_code": "MO", "name": "Macau", "min_length": 8, "max_length": 9 },
    { "code": "+389", "short_code": "MK", "name": "Macedonia", "min_length": 8, "max_length": 9 },
    { "code": "+261", "short_code": "MG", "name": "Madagascar", "min_length": 9, "max_length": 10 },
    { "code": "+265", "short_code": "MW", "name": "Malawi", "min_length": 9, "max_length": 10 },
    { "code": "+60", "short_code": "MY", "name": "Malaysia", "min_length": 9, "max_length": 10 },
    { "code": "+960", "short_code": "MV", "name": "Maldives", "min_length": 7, "max_length": 8 },
    { "code": "+223", "short_code": "ML", "name": "Mali", "min_length": 8, "max_length": 9 },
    { "code": "+356", "short_code": "MT", "name": "Malta", "min_length": 8, "max_length": 9 },
    { "code": "+692", "short_code": "MH", "name": "Marshall Islands", "min_length": 7, "max_length": 8 },
    { "code": "+222", "short_code": "MR", "name": "Mauritania", "min_length": 8, "max_length": 9 },
    { "code": "+230", "short_code": "MU", "name": "Mauritius", "min_length": 8, "max_length": 9 },
    { "code": "+262", "short_code": "YT", "name": "Mayotte", "min_length": 8, "max_length": 9 },
    { "code": "+52", "short_code": "MX", "name": "Mexico", "min_length": 10, "max_length": 11 },
    { "code": "+691", "short_code": "FM", "name": "Micronesia", "min_length": 7, "max_length": 8 },
    { "code": "+373", "short_code": "MD", "name": "Moldova", "min_length": 8, "max_length": 9 },
    { "code": "+377", "short_code": "MC", "name": "Monaco", "min_length": 9, "max_length": 10 },
    { "code": "+976", "short_code": "MN", "name": "Mongolia", "min_length": 8, "max_length": 9 },
    { "code": "+382", "short_code": "ME", "name": "Montenegro", "min_length": 9, "max_length": 10 },
    { "code": "+1-664", "short_code": "MS", "name": "Montserrat", "min_length": 9, "max_length": 10 },
    { "code": "+212", "short_code": "MA", "name": "Morocco", "min_length": 10, "max_length": 11 },
    { "code": "+258", "short_code": "MZ", "name": "Mozambique", "min_length": 9, "max_length": 10 },
    { "code": "+95", "short_code": "MM", "name": "Myanmar", "min_length": 9, "max_length": 10 },
    { "code": "+264", "short_code": "NA", "name": "Namibia", "min_length": 8, "max_length": 9 },
    { "code": "+674", "short_code": "NR", "name": "Nauru", "min_length": 6, "max_length": 7 },
    { "code": "+977", "short_code": "NP", "name": "Nepal", "min_length": 10, "max_length": 11 },
    { "code": "+31", "short_code": "NL", "name": "Netherlands", "min_length": 11, "max_length": 12 },
    { "code": "+687", "short_code": "NC", "name": "New Caledonia", "min_length": 8, "max_length": 9 },
    { "code": "+64", "short_code": "NZ", "name": "New Zealand", "min_length": 11, "max_length": 12 },
    { "code": "+505", "short_code": "NI", "name": "Nicaragua", "min_length": 8, "max_length": 9 },
    { "code": "+227", "short_code": "NE", "name": "Niger", "min_length": 7, "max_length": 8 },
    { "code": "+234", "short_code": "NG", "name": "Nigeria", "min_length": 10, "max_length": 11 },
    { "code": "+683", "short_code": "NU", "name": "Niue", "min_length": 6, "max_length": 7 },
    { "code": "+672", "short_code": "NF", "name": "Norfolk Island", "min_length": 14, "max_length": 15 },
    { "code": "+850", "short_code": "KP", "name": "North Korea", "min_length": 9, "max_length": 10 },
    { "code": "+1-670", "short_code": "MP", "name": "Northern Mariana Islands", "min_length": 9, "max_length": 10 },
    { "code": "+47", "short_code": "NO", "name": "Norway", "min_length": 10, "max_length": 11 },
    { "code": "+968", "short_code": "OM", "name": "Oman", "min_length": 8, "max_length": 9 },
    { "code": "+92", "short_code": "PK", "name": "Pakistan", "min_length": 10, "max_length": 11 },
    { "code": "+680", "short_code": "PW", "name": "Palau", "min_length": 7, "max_length": 8 },
    { "code": "+970", "short_code": "PS", "name": "Palestine", "min_length": 10, "max_length": 11 },
    { "code": "+507", "short_code": "PA", "name": "Panama", "min_length": 8, "max_length": 9 },
    { "code": "+675", "short_code": "PG", "name": "Papua New Guinea", "min_length": 8, "max_length": 9 },
    { "code": "+595", "short_code": "PY", "name": "Paraguay", "min_length": 9, "max_length": 10 },
    { "code": "+51", "short_code": "PE", "name": "Peru", "min_length": 10, "max_length": 11 },
    { "code": "+63", "short_code": "PH", "name": "Philippines", "min_length": 10, "max_length": 11 },
    { "code": "+64", "short_code": "PN", "name": "Pitcairn Islands", "min_length": 10, "max_length": 11 },
    { "code": "+48", "short_code": "PL", "name": "Poland", "min_length": 9, "max_length": 10 },
    { "code": "+351", "short_code": "PT", "name": "Portugal", "min_length": 9, "max_length": 10 },
    { "code": "+1-787", "short_code": "PR", "name": "Puerto Rico", "min_length": 9, "max_length": 10 },
    { "code": "+1-939", "short_code": "PR", "name": "Puerto Rico", "min_length": 9, "max_length": 10 },
    { "code": "+974", "short_code": "QA", "name": "Qatar", "min_length": 8, "max_length": 9 },
    { "code": "+242", "short_code": "CG", "name": "Republic of the Congo", "min_length": 8, "max_length": 9 },
    { "code": "+262", "short_code": "RE", "name": "Reunion", "min_length": 8, "max_length": 9 },
    { "code": "+40", "short_code": "RO", "name": "Romania", "min_length": 9, "max_length": 10 },
    { "code": "+7", "short_code": "RU", "name": "Russia", "min_length": 11, "max_length": 12 },
    { "code": "+250", "short_code": "RW", "name": "Rwanda", "min_length": 9, "max_length": 10 },
    { "code": "+590", "short_code": "BL", "name": "Saint Barthelemy", "min_length": 8, "max_length": 9 },
    { "code": "+290", "short_code": "SH", "name": "Saint Helena", "min_length": 8, "max_length": 9 },
    { "code": "+1-869", "short_code": "KN", "name": "Saint Kitts and Nevis", "min_length": 9, "max_length": 10 },
    { "code": "+1-758", "short_code": "LC", "name": "Saint Lucia", "min_length": 9, "max_length": 10 },
    { "code": "+590", "short_code": "MF", "name": "Saint Martin", "min_length": 8, "max_length": 9 },
    { "code": "+508", "short_code": "PM", "name": "Saint Pierre and Miquelon", "min_length": 9, "max_length": 10 },
    { "code": "+1-784", "short_code": "VC", "name": "Saint Vincent and the Grenadines", "min_length": 9, "max_length": 10 },
    { "code": "+685", "short_code": "WS", "name": "Samoa", "min_length": 7, "max_length": 8 },
    { "code": "+378", "short_code": "SM", "name": "San Marino", "min_length": 8, "max_length": 9 },
    { "code": "+239", "short_code": "ST", "name": "Sao Tome and Principe", "min_length": 7, "max_length": 8 },
    { "code": "+966", "short_code": "SA", "name": "Saudi Arabia", "min_length": 9, "max_length": 10 },
    { "code": "+221", "short_code": "SN", "name": "Senegal", "min_length": 9, "max_length": 10 },
    { "code": "+381", "short_code": "RS", "name": "Serbia", "min_length": 9, "max_length": 10 },
    { "code": "+248", "short_code": "SC", "name": "Seychelles", "min_length": 7, "max_length": 8 },
    { "code": "+232", "short_code": "SL", "name": "Sierra Leone", "min_length": 8, "max_length": 9 },
    { "code": "+65", "short_code": "SG", "name": "Singapore", "min_length": 8, "max_length": 9 },
    { "code": "+1-721", "short_code": "SX", "name": "Sint Maarten", "min_length": 9, "max_length": 10 },
    { "code": "+421", "short_code": "SK", "name": "Slovakia", "min_length": 9, "max_length": 10 },
    { "code": "+386", "short_code": "SI", "name": "Slovenia", "min_length": 9, "max_length": 10 },
    { "code": "+677", "short_code": "SB", "name": "Solomon Islands", "min_length": 7, "max_length": 8 },
    { "code": "+252", "short_code": "SO", "name": "Somalia", "min_length": 8, "max_length": 9 },
    { "code": "+27", "short_code": "ZA", "name": "South Africa", "min_length": 10, "max_length": 11 },
    { "code": "+82", "short_code": "KR", "name": "South Korea", "min_length": 10, "max_length": 11 },
    { "code": "+211", "short_code": "SS", "name": "South Sudan", "min_length": 8, "max_length": 9 },
    { "code": "+34", "short_code": "ES", "name": "Spain", "min_length": 10, "max_length": 11 },
    { "code": "+94", "short_code": "LK", "name": "Sri Lanka", "min_length": 9, "max_length": 10 },
    { "code": "+249", "short_code": "SD", "name": "Sudan", "min_length": 9, "max_length": 10 },
    { "code": "+597", "short_code": "SR", "name": "Suriname", "min_length": 7, "max_length": 8 },
    { "code": "+47", "short_code": "SJ", "name": "Svalbard and Jan Mayen", "min_length": 10, "max_length": 11 },
    { "code": "+268", "short_code": "SZ", "name": "Swaziland", "min_length": 8, "max_length": 9 },
    { "code": "+46", "short_code": "SE", "name": "Sweden", "min_length": 10, "max_length": 11 },
    { "code": "+41", "short_code": "CH", "name": "Switzerland", "min_length": 10, "max_length": 11 },
    { "code": "+963", "short_code": "SY", "name": "Syria", "min_length": 10, "max_length": 11 },
    { "code": "+886", "short_code": "TW", "name": "Taiwan", "min_length": 9, "max_length": 10 },
    { "code": "+992", "short_code": "TJ", "name": "Tajikistan", "min_length": 9, "max_length": 10 },
    { "code": "+255", "short_code": "TZ", "name": "Tanzania", "min_length": 10, "max_length": 11 },
    { "code": "+66", "short_code": "TH", "name": "Thailand", "min_length": 9, "max_length": 10 },
    { "code": "+670", "short_code": "TL", "name": "Timor-Leste", "min_length": 8, "max_length": 9 },
    { "code": "+228", "short_code": "TG", "name": "Togo", "min_length": 8, "max_length": 9 },
    { "code": "+690", "short_code": "TK", "name": "Tokelau", "min_length": 6, "max_length": 7 },
    { "code": "+676", "short_code": "TO", "name": "Tonga", "min_length": 6, "max_length": 7 },
    { "code": "+1-868", "short_code": "TT", "name": "Trinidad and Tobago", "min_length": 9, "max_length": 10 },
    { "code": "+216", "short_code": "TN", "name": "Tunisia", "min_length": 8, "max_length": 9 },
    { "code": "+90", "short_code": "TR", "name": "Turkey", "min_length": 10, "max_length": 11 },
    { "code": "+993", "short_code": "TM", "name": "Turkmenistan", "min_length": 8, "max_length": 9 },
    { "code": "+1-649", "short_code": "TC", "name": "Turks and Caicos Islands", "min_length": 9, "max_length": 10 },
    { "code": "+688", "short_code": "TV", "name": "Tuvalu", "min_length": 6, "max_length": 7 },
    { "code": "+1-340", "short_code": "VI", "name": "U.S. Virgin Islands", "min_length": 9, "max_length": 10 },
    { "code": "+256", "short_code": "UG", "name": "Uganda", "min_length": 10, "max_length": 11 },
    { "code": "+380", "short_code": "UA", "name": "Ukraine", "min_length": 9, "max_length": 10 },
    { "code": "+971", "short_code": "AE", "name": "United Arab Emirates", "min_length": 9, "max_length": 10 },
    { "code": "+44", "short_code": "GB", "name": "United Kingdom", "min_length": 11, "max_length": 12 },
    { "code": "+1", "short_code": "US", "name": "United States", "min_length": 10, "max_length": 11 },
    { "code": "+598", "short_code": "UY", "name": "Uruguay", "min_length": 9, "max_length": 10 },
    { "code": "+998", "short_code": "UZ", "name": "Uzbekistan", "min_length": 9, "max_length": 10 },
    { "code": "+678", "short_code": "VU", "name": "Vanuatu", "min_length": 7, "max_length": 8 },
    { "code": "+379", "short_code": "VA", "name": "Vatican", "min_length": 10, "max_length": 11 },
    { "code": "+58", "short_code": "VE", "name": "Venezuela", "min_length": 10, "max_length": 11 },
    { "code": "+84", "short_code": "VN", "name": "Vietnam", "min_length": 10, "max_length": 11 },
    { "code": "+681", "short_code": "WF", "name": "Wallis and Futuna", "min_length": 8, "max_length": 9 },
    { "code": "+212", "short_code": "EH", "name": "Western Sahara", "min_length": 10, "max_length": 11 },
    { "code": "+967", "short_code": "YE", "name": "Yemen", "min_length": 9, "max_length": 10 },
    { "code": "+260", "short_code": "ZM", "name": "Zambia", "min_length": 9, "max_length": 10 },
    { "code": "+263", "short_code": "ZW", "name": "Zimbabwe", "min_length": 10, "max_length": 11 }
]
